name: flutterwarden
description: A flutter client for Bitwarden password manager.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  ant_icons: ^1.0.0
  cached_network_image: ^2.3.3
  expandable: ^4.1.4

  # Dependency Injection
  get_it: ^5.0.1
  injectable: ^1.0.5

  # State management
  bloc: ^6.1.0
  flutter_bloc: ^6.1.0

  # Dart data class
  json_serializable: ^3.5.0
  freezed_annotation: ^0.12.0

  # Network
  data_connection_checker: ^0.3.4
  url_launcher: ^5.7.10
  http: ^0.12.2

  # Local cache
  hive: ^1.4.4+1

  # Cryptography
  pointycastle: ^2.0.0
  encrypt: ^4.1.0
  cryptography: ^0.3.0

  # Routing
  auto_route: ^0.6.9

  # Logging
  logger: ^0.9.4

  # Fingerprint authentication
  local_auth: ^0.6.3+4

  # Misc
  dartz: ^0.9.2
  rxdart: ^0.24.1
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  freezed: ^0.12.2
  build_runner: ^1.10.4
  auto_route_generator: ^0.6.10
  injectable_generator: ^1.0.6

  # Linting
  effective_dart: ^1.3.0

  # Testing
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true
