name: flutterwarden
description: A flutter client for Bitwarden password manager.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  ant_icons: ^2.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  expandable: ^5.0.1

  # Dependency Injection
  get_it: ^7.1.3
  injectable: ^1.4.0

  # State management
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

  # Dart data class
  json_serializable: ^4.1.1
  freezed_annotation: ^0.14.1

  # Network
  data_connection_checker:
    git: 
      url: https://github.com/uSlashVlad/data_connection_checker.git
  url_launcher: ^6.0.3
  http: ^0.13.3

  # Local cache
  hive: ^2.0.4

  # Cryptography
  pointycastle: ^3.0.1
  encrypt: ^5.0.0
  cryptography: ^2.0.1

  # Routing
  auto_route: ^2.2.0

  # Logging
  logger: ^1.0.0

  # Fingerprint authentication
  local_auth: ^1.1.5

  # Misc
  dartz: ^0.10.0-nullsafety.2
  rxdart: ^0.26.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  freezed: ^0.14.1+3
  build_runner: ^2.0.2
  auto_route_generator: ^2.1.0
  injectable_generator: ^1.4.0

  # Linting
  effective_dart: ^1.3.1

flutter:
  uses-material-design: true
